import { Activity, CircleCheck, Shield, TriangleAlert } from "lucide-react";
import { Recipient } from "./types";

export const initialRecipients: Recipient[] = [
  {
    id: "1",
    name: "Dana Whitman",
    email: "dana@acme.io",
    initials: "DW",
    isYou: true,
    scope: "All monitors",
    scopeVariant: "default",
    enabled: true,
  },
  {
    id: "2",
    name: "Ryan Soto",
    email: "ryan@acme.io",
    initials: "RS",
    isYou: false,
    scope: "All monitors",
    scopeVariant: "default",
    enabled: true,
  },
  {
    id: "3",
    name: "On-call",
    email: "oncall@acme.io",
    initials: "O",
    isYou: false,
    scope: "Critical only",
    scopeVariant: "blue",
    enabled: true,
  },
  {
    id: "4",
    name: "Maya Kim",
    email: "maya@acme.io",
    initials: "MK",
    isYou: false,
    scope: "Checkout, API",
    scopeVariant: "blue",
    enabled: true,
  },
  {
    id: "5",
    name: "Status Bot",
    email: "alerts@acme.pagerduty.com",
    initials: "SB",
    isYou: false,
    scope: "All monitors",
    scopeVariant: "default",
    enabled: true,
  },
];

export const alertTypes = [
  {
    id: crypto.randomUUID(),
    icon: TriangleAlert,
    color: "red",
    eventType: "Monitor goes down",
    description: "Send the moment a monitor crosses its failure threshold",
    enabled: true,
    isLast: false,
  },
  {
    id: crypto.randomUUID(),
    icon: CircleCheck,
    color: "green",
    eventType: "Monitor recovers",
    description: "Send when a monitor returns to a healthy state",
    enabled: true,
    isLast: false,
  },
  {
    id: crypto.randomUUID(),
    icon: Activity,
    color: "amber",
    eventType: "Degraded performance",
    description: "Send when response time exceeds the configured threshold",
    enabled: true,
    isLast: false,
  },
  {
    id: crypto.randomUUID(),
    icon: Shield,
    color: "blue",
    eventType: "SSL certificate expiring",
    description: "Warn 14, 7 and 1 day before a certificate expires",
    enabled: true,
    isLast: true,
  },
];
